version: '3'
services:
    postgres:
        image: postgres:10-alpine
        networks:
            - appnet
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql
            - ./database/postgres/data:/data
        hostname: postgres
        environment:
            POSTGRES_USER: nano
            POSTGRES_PASSWORD: chan
            POSTGRES_DB: nanochan

    # Redis database
    redis:
        image: 'redis:alpine'
        networks:
            - appnet
        hostname: redis


    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        networks:
            - appnet
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        hostname: api
        depends_on:
            - postgres
            - redis

networks:
    appnet:

# vim: et:sw=4:tw=4
